export const DAY_STRIP_HOUR_MS = 60 * 60 * 1000;
export const DAY_STRIP_FORWARD_WINDOW_HOURS = 12;
export const DAY_STRIP_FORWARD_WINDOW_MS = DAY_STRIP_FORWARD_WINDOW_HOURS * DAY_STRIP_HOUR_MS;
export const DAY_STRIP_KEYBOARD_SLOT_MS = 15 * 60 * 1000;
