export const DEFAULT_TIMEZONE = 'UTC';

export const WEEKDAY_MAP: Record<string, number> = {
  sunday: 0,
  sun: 0,
  monday: 1,
  mon: 1,
  tuesday: 2,
  tue: 2,
  tues: 2,
  wednesday: 3,
  wed: 3,
  thursday: 4,
  thu: 4,
  thur: 4,
  thurs: 4,
  friday: 5,
  fri: 5,
  saturday: 6,
  sat: 6,
};

export const WEEKDAY_SET = new Set(Object.keys(WEEKDAY_MAP));

export const TITLE_CORRECTIONS: Record<string, string> = {
  abt: 'about',
  adn: 'and',
  b4: 'before',
  brng: 'bring',
  callin: 'call',
  cancle: 'cancel',
  cehck: 'check',
  clint: 'client',
  dattabase: 'database',
  delivry: 'delivery',
  dashbord: 'dashboard',
  electrican: 'electrician',
  evry: 'every',
  flrs: 'flowers',
  flowrs: 'flowers',
  forgt: 'forget',
  hr: 'HR',
  hub: 'hub',
  meetting: 'meeting',
  meds: 'meds',
  mornig: 'morning',
  mornng: 'morning',
  moms: "mom's",
  mums: "mum's",
  pakage: 'package',
  passport: 'passport',
  pickup: 'pick up',
  prescirption: 'prescription',
  propsal: 'proposal',
  refil: 'refill',
  rememeber: 'remember',
  remnd: 'remind',
  rent: 'rent',
  reveiw: 'review',
  revieww: 'review',
  subsription: 'subscription',
  teh: 'the',
  tongiht: 'tonight',
};

export const ACRONYM_MAP: Record<string, string> = {
  eod: 'EOD',
  fcp: 'FCP',
  hr: 'HR',
  os: 'OS',
  svg: 'SVG',
  usb: 'USB',
};

export const PREFIX_FILLER_PATTERNS: RegExp[] = [
  /^(?:\p{Emoji}|\p{Emoji_Modifier}|\p{Emoji_Component}|\uFE0F|\u200D|\s|[!?.,:;-])+/u,
  /^\s*hey siri i mean claude\b[\s,:-]*/i,
  /^\s*(?:hey|yo|pls|please)\b[\s,:-]*/i,
];

export const PREFIX_PATTERNS: RegExp[] = [
  /\bpls\s+remind\s+me\s+to\b/i,
  /\bpls\s+remind\s+me\b/i,
  /\bplease\s+to\s+remind\s+me\s+about\b/i,
  /\bplease\s+to\s+remind\s+me\b/i,
  /\bhey\s+remind\s+me\b/i,
  /\byo\s+remind\s+me\b/i,
  /\bgotta\s+remember\s+to\b/i,
  /\bneed\s+to\s+remember\b/i,
  /\bneed\s+to\s+remembr\s+to\b/i,
  /\bi should probably remember to\b/i,
  /\bremind\s*me\s+to\b/i,
  /\bremind\s*me\s+about\b/i,
  /\bremind\s*me\s+that\b/i,
  /\bremind\s*me\s+2\b/i,
  /\bremind\s*me\s+two\b/i,
  /\bremind\s*me\b/i,
  /\bremindme\s+to\b/i,
  /\bremindme\b/i,
  /\brmind\s+me\b/i,
  /\bremnd me\b/i,
  /\bremmber\s+to\b/i,
  /\brememeber\b/i,
  /\bremember\s+to\b/i,
  /\bremember\b/i,
  /\bdon'?t\s+let\s+me\s+forget\s+about\b/i,
  /\bdon'?t\s+forget\s+to\b/i,
  /\bdon'?t\s+forget\b/i,
  /\bdont\s+forget\s+to\b/i,
  /\bdont\s+forget\b/i,
  /\bdont\s+foreget\b/i,
  /\bdont\s+fore?get\b/i,
  /\bdont\s+let\s+me\s+forgt\b/i,
  /\bdont\s+let\s+me\s+forget\b/i,
  /\bdont\s+4get\b/i,
  /\bnote\s+to\s+self\b/i,
  /\bping\s+me\s+about\b/i,
  /\bping\s+me\s+to\b/i,
  /\bping\s+me\b/i,
  /\bheads\s+up\b/i,
];

export const TRAILING_FILLER_PATTERNS: RegExp[] = [
  /[\s,.-]+\blol\b[!?.]*$/i,
  /[\s,.-]+\bpls\b[!?.]*$/i,
  /[\s,.-]+\bplease\b[!?.]*$/i,
  /[!?.]+$/i,
];

export const START_STRIP_PATTERNS: RegExp[] = [
  /^\s*(?:to|about|that|re:|re|abt|bout)\b[\s,:-]*/i,
  /^\s*for\b[\s,:-]*/i,
];

export const RECURRENCE_DAY_LIST = '(?:mon(?:day)?|tue(?:s|sday)?|wed(?:nesday)?|thu(?:r|rs|rsday|ursday)?|fri(?:day)?|sat(?:urday)?|sun(?:day)?)';

export const TIME_PREPROCESS_REPLACEMENTS: Array<[RegExp, string | ((...args: string[]) => string)]> = [
  [/\btmrw\b/gi, 'tomorrow'],
  [/\btmr\b/gi, 'tomorrow'],
  [/\btomorow\b/gi, 'tomorrow'],
  [/\bfirday\b/gi, 'friday'],
  [/\bwedensday\b/gi, 'wednesday'],
  [/\bon wed\b/gi, 'on wednesday'],
  [/\bmornig\b/gi, 'morning'],
  [/\bmornng\b/gi, 'morning'],
  [/\btongiht\b/gi, 'tonight'],
  [/\bthis aft\b/gi, 'this afternoon'],
  [/\barvo\b/gi, 'arvo'],
  [/\bin lke (\d+)\s*min\b/gi, 'in $1 minutes'],
  [/\bin (\d+)\s*min\b/gi, 'in $1 minutes'],
  [/\bin (\d+)\s*hr\b/gi, 'in $1 hours'],
  [/\b(tomorrow|monday|tuesday|wednesday|thursday|friday|saturday|sunday)\s+(\d{1,2})(?!\d|:|\s*(?:am|pm))\b/gi, '$1 at $2am'],
  [/\bat (\d{1,2})(?!\d|:|\s*(?:am|pm))\b/gi, (_m, hour: string) => `at ${hour}${Number(hour) <= 6 ? 'pm' : 'am'}`],
  [/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\s+(\d{1,2})(?!\d|:|\s*(?:am|pm))\b/gi, '$1 at $2am'],
  [/\bhalf\s+(\d{1,2})\b/gi, (_m, hour: string) => `${hour}:30pm`],
  [/\bto PM\b/g, '2 PM'],
  [/\bat to PM\b/g, 'at 2 PM'],
  [/\blunchtime\b/gi, '12pm'],
];
